### ISSUE TITLE
[Revamp] 更新虚拟机登录与文件传输

### ISSUE THREAD

**Issue by iBug** [USTC-vlab/docs#4]
重发一遍 #3，这次用 issue 和 checkbox 跟踪进度

---

我们的 SSH 登录方式已经全面切换至统一登录接口，需要更新对应的文档，并增加文件传输的指导。文档需要覆盖几种常见的软件，如：

- [x] PuTTY（已有部分内容）
- [ ] XShell
- [x] FileZilla
- [ ] WinSCP
- [x] 命令行使用 `ssh` 登录

@yanchaomei: 由于秋季学期课程已经开始，希望这部分内容能尽快完成。所有需要更新的内容均已标记上 "TBD"，可以观察 `grep -nriF tbd docs/` 的输出来确定它们的位置。

每完成一项请将其勾上，注意该列表后续会增加新项目。

<details>
<summary>TBD 标记</summary>

![image](https://user-images.githubusercontent.com/7273074/96334777-ca067080-10a5-11eb-8ff8-15f94e890379.png)

</details>

**Comment by taoky** [comment]
Note: 公钥登录需要加上权限（不能 too open）相关的说明与解决方法 (`chmod 600 xxx.pem`)
